#!/bin/bash
cd /root/bin/
#you have to provide hosts file (prometheus syntax) to these scripts
#/root/bin/updatehosts
/root/bin/make-pimp
/root/bin/make-iptables-restore
#our firewall is configured before restoring iptables nat table
#/etc/network/setnet
echo -n "Running iptables restore ... "
/sbin/iptables-restore < /mnt/mtdblock0/iptables-restore.in
echo "done."
