#!/bin/bash
cd /root/bin/
/root/bin/updatehosts
/root/bin/make-pimp
/root/bin/make-iptables-restore
/etc/network/setnet
#echo -n "Running iptables restore ... "
#/sbin/iptables-restore < /mnt/mtdblock0/iptables-restore.in
#echo "done."
